SNAKE_SIZE = 15
GAME_WIDTH = 50
GAME_HEIGHT = 50
GAME_MAX_FPS = 144
WINDOW_WIDTH = GAME_WIDTH * SNAKE_SIZE
WINDOW_HEIGHT = GAME_HEIGHT * SNAKE_SIZE

SELECTION_MAX_SIZE = 60
SELECTION_MIN_SIZE = 40
SELECTION_SEP_SIZE = 10
SELECT_ANIMATION_MAX_TIME = 0.2

DEFAULT_TEXT_FONT_NAME = "Microsoft YaHei"

SSAA = 4  # SSAA 16x

GAME_HELP_TEXT = (
    "按下方向键或WASD键移动。\n食物有四种：\n灰色无特殊效果，红色可加快速度，蓝色可减慢速度，金色可得到双倍分数。\n按下ESC退出帮助页面。"
)

SNAKE_INITIAL_LENGTH = 3